// POST /api/nutrition/name-meal
//
// Returns a short meal name (max 40 chars) generated by Claude.
// Called by ScreenConfirm when mealName is empty and no library recipe
// name was pre-filled. No DB writes.
//
// Body: {
//   items?: Array<{ name: string; weight_grams: number }>  // ingredient-assembled meals
// }
//
// Response: { name: string }

import Anthropic from '@anthropic-ai/sdk'

interface NameMealBody {
  items?: Array<{ name: string; weight_grams: number }>
}

export async function POST(req: Request) {
  let body: NameMealBody
  try { body = await req.json() as NameMealBody } catch {
    return Response.json({ error: 'parse-body' }, { status: 400 })
  }

  const items = body.items ?? []
  if (items.length === 0) {
    return Response.json({ name: '' })
  }

  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) {
    return Response.json({ error: 'ANTHROPIC_API_KEY not set' }, { status: 500 })
  }

  const ingredientList = items.map(it => `${it.name} (${it.weight_grams}g)`).join(', ')
  const userPrompt = `Ingredients: ${ingredientList}.\n\nReturn only a meal name, maximum 40 characters, INCLUDING spaces — count the characters before answering. The name must be a complete, natural-sounding phrase, not a sentence fragment or a name that trails off (e.g. "Grilled chicken with roasted" is wrong — either finish the thought within the limit or pick a shorter complete phrase that captures the meal, like "Grilled chicken & veg"). Descriptive and food-forward (e.g. "Greek yogurt & berry bowl", "Pulled chicken sandwich"). Never time-of-day based. If the full ingredient list can't fit as a complete phrase within 40 characters, summarize to the most defining ingredients rather than truncating a longer name. No preamble, no punctuation wrapping — just the name.`

  try {
    const client = new Anthropic({ apiKey })
    const message = await client.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 60,
      messages: [{ role: 'user', content: userPrompt }],
    })
    const first = message.content[0]
    const raw = first?.type === 'text' ? first.text.trim() : ''
    // Strip any accidental quotes the model may add
    const stripped = raw.replace(/^["']|["']$/g, '').trim()
    // The prompt asks the model to produce a complete phrase that already fits within
    // 40 chars — this is a safety-net fallback only, in case it doesn't comply.
    // Truncate at the last word boundary before the limit — no mid-word cut, no "..." appended.
    const name = stripped.length <= 40
      ? stripped
      : (stripped.slice(0, 40).replace(/\s+\S*$/, '') || stripped.slice(0, 40))
    return Response.json({ name })
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e)
    return Response.json({ error: msg }, { status: 500 })
  }
}
